name: Build and Push to Docker Hub

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x, "18.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm ci

      - name: tests
        run: npm test

      - name: tests
        run: npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: tests # Only run Docker job if the tests pass

    steps:
      - uses: actions/checkout@v2

      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/azure-react:${{ github.sha }} .

      # Step 3: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/azure-react:${{ github.sha }}

      # Optionally, tag the image as latest
      - name: Tag Docker image as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/azure-react:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/azure-react:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/azure-react:latest
